### ISSUE TITLE
change directory for images in article?

### ISSUE THREAD

**Issue by MrMichael3** [Rise-in-Time/rise-in-time-orb#35]
Should we change the directory to find images for the articles in the function "getImageStyle"? Currently, you can only write the name of the image in the json file of an article. But that means every image must be in the same folder. The images are in a different folder structure. When we change it, we can keep the different folders but have to write which folder the image is in in the json. What do you prefer Armin?

![image](https://user-images.githubusercontent.com/33421646/120895710-835a8c00-c61e-11eb-84e7-054f94a86279.png)

**Comment by ArminWindlin** [comment]
Uhh GitHub issues, never used that before.

Isn't it convenient to not have to worry about where to place/fetch the images, by having all article images in the same place?
What is the issue/disadvantages with having them in the same folder (currently I can't see any, but open for good points :)?

**Comment by MrMichael3** [comment]
Currently we have images doubled. In the folder structure units and in the articles folder. We can do no folder structure and put all images together or structure them in different folders. Or we double all images like we do now

**Comment by ArminWindlin** [comment]
Oh, I see what you mean. I think this problem is mainly with the units for now. I still think it's better to keep all article images in the same folder, to keep the article JSON and making articles as simple as possible. I would suggest either keep them duplicate or to also use the articles folder where the unit images have been used otherwise (I think they are only used in treasure table and fetched in images.scss).

**Comment by MrMichael3** [comment]
check
